[package]
name = "journey"
version = "0.1.0"
description = "A Tauri App"
authors = ["leuchthelp"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "journey_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[workspace]
resolver = "3"
members = [
    "journey-api",
    "journey-db",
    "journey-keyring",
    "journey-media-item",
    "journey-playback",
    "journey-provider",
    "journey-utils",
]

[workspace.dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-persisted-scope = "2"
tauri-plugin-os = "2"
tauri-plugin-fs = "2"
tauri-plugin-window-state = "2"

serial_test = "4"
test-log = { version = "0.2", features = ["trace"] }
tracing-test = "0.2.6"

anyhow = "1"
inherent = "1"
thiserror = "2"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v7", "zerocopy"] }
bon = "3"
similar = "3"
rapidhash = "4"
async-trait = "0.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

specta = { version = "2.0.0-rc.25", features = [
    "derive",
    "uuid",
    "url",
    "tokio",
    "jiff",
] }
specta-typescript = "0.0.12"
specta-serde = { version = "0.0.12" }
taurpc = "0.8"

journey-db = { path = "journey-db" }
chrono = "0.4"
strum = "0.28"
strum_macros = "0.28"
sea-orm = { version = "2", features = [
    "sqlx-sqlite",
    "runtime-tokio",
    "macros",
    "schema-sync",
    "entity-registry",
    "serde",
    "with-uuid",
    "with-json",
] }
sea-query = "1"


journey-api = { path = "journey-api" }


futures = "0.3"

journey-provider = { path = "journey-provider" }
dyn-clone = "1"
kameo = "0.22"
jiff = { version = "0.2", features = ["serde"] }
jellyfin-sdk-rs = { git = "https://github.com/leuchthelp/jellyfin-sdk-rs", branch = "master" }


journey-media-item = { path = "journey-media-item" }

journey-playback = { path = "journey-playback" }
reqwest = "0.13"
stream-download = { version = "0.24", features = ["async-read"] }
rodio = { version = "0.22", features = [
    "symphonia-alac",
    "symphonia-simd",
    "symphonia-mkv",
] }

journey-utils = { path = "journey-utils" }
dotenvy = { git = "https://github.com/allan2/dotenvy", features = ["macros"] }

journey-keyring = { path = "journey-keyring" }


[workspace.lints.rust]
unsafe_code = "forbid"
unconditional_panic = "forbid"

[dependencies]
tauri = { workspace = true }
tauri-plugin-persisted-scope = { workspace = true }
tauri-plugin-os = { workspace = true }
tauri-plugin-fs = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
taurpc = { workspace = true }
anyhow = { workspace = true }
journey-api = { workspace = true }
journey-keyring = { workspace = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = { workspace = true }
