[package]
name = "journey"
version = "0.1.0"
description = "A Tauri App"
authors = ["leuchthelp"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "journey_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[workspace]
resolver = "3"
members = ["journey-db", "journey-keyring", "journey-provider", "journey-utils"]

[workspace.dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-persisted-scope = "2"
tauri-plugin-fs = "2"
tauri-plugin-log = "2"
tauri-plugin-os = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
taurpc = "0.8.2"
specta = { version = "2.0.0-rc.25", features = ["derive", "uuid"] }
specta-typescript = "0.0.12"
log = "0.4"
bon = "3.9"
url = "2.5.8"
chrono = "0.4.45"
reqwest = "0.13.4"
thiserror = "2.0.19"
async-trait = "0.1.91"
anyhow = "1.0.104"
serial_test = "3.5.0"
uuid = { version = "^1.23.4", features = ["serde", "v7"] }
sea-orm = { version = "2.0.0-rc.43", features = [
    "sqlx-sqlite",
    "runtime-tokio",
    "macros",
    "with-uuid",
    "schema-sync",
    "entity-registry",
    "with-json",
] }
journey-db = { path = "journey-db" }
journey-utils = { path = "journey-utils" }
journey-keyring = { path = "journey-keyring" }
journey-provider = { path = "journey-provider" }

dotenvy = { git = "https://github.com/allan2/dotenvy", features = ["macros"] }


[workspace.lints.rust]
unsafe_code = "forbid"
unconditional_panic = "forbid"

[dependencies]
tauri = { workspace = true }
tauri-plugin-opener = { workspace = true }
tauri-plugin-persisted-scope = { workspace = true }
tauri-plugin-fs = { workspace = true }
tauri-plugin-log = { workspace = true }
tauri-plugin-os = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
taurpc = { workspace = true }
specta = { workspace = true }
specta-typescript = { workspace = true }
log = { workspace = true }
sea-orm = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }
journey-db = { workspace = true }
journey-keyring = { workspace = true }
journey-provider = { workspace = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2"
