// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
export type ContentApiError = string;

export type ContentDTO = {
	id: number,
	parentId: string | null,
	parent: MediaItemDTO | null,
	type: string,
	description: string,
};

export type ImageApiError = string;

export type ImageDTO = {
	url: string,
	serverId: string | null,
	provider: ProviderDTO | null,
	type: string,
	mediaItems: MediaItemDTO[] | null,
};

export type MediaItemApiError = string;

export type MediaItemDTO = {
	uuid: string,
	type: string,
	outlineGradient: string,
	loaded: boolean,
	local: string,
	original: OriginalDTO[] | null,
	content: ContentDTO[] | null,
	providers: ProviderDTO[] | null,
	images: ImageDTO[] | null,
	children: MediaItemDTO[] | null,
	parents: MediaItemDTO[] | null,
};

export type OriginalApiError = string;

export type OriginalDTO = {
	id: number,
	parentId: string | null,
	parent: MediaItemDTO | null,
	serverId: string,
	url: string,
};

export type ProviderApiError = string;

export type ProviderDTO = {
	authenticated: boolean,
	hash: number,
	serverId: string | null,
	userId: string | null,
	type: string,
	url: string | null,
	mediaItems: MediaItemDTO[] | null,
	images: ImageDTO[] | null,
};

export type Result<T, E> = {
	ok: T,
	err: E,
};
const ARGS_MAP = {"content":{"get_content":[]},"image":{"get_images":[]},"mediaItem":{"get_media_items":[]},"original":{"get_original":[]},"provider":{"get_provider":["key"],"get_providers":[]}};

const RESULT_MAP = {"content":{"get_content":true},"image":{"get_images":true},"mediaItem":{"get_media_items":true},"original":{"get_original":true},"provider":{"get_provider":true,"get_providers":true}};

export type Router = {
	content: {
		get_content: () => Promise<TauRpcResult<ContentDTO, ContentApiError>>,
	},
	image: {
		get_images: () => Promise<TauRpcResult<ImageDTO, ImageApiError>>,
	},
	mediaItem: {
		get_media_items: () => Promise<TauRpcResult<MediaItemDTO, MediaItemApiError>>,
	},
	original: {
		get_original: () => Promise<TauRpcResult<OriginalDTO, OriginalApiError>>,
	},
	provider: {
		get_provider: (key: number) => Promise<TauRpcResult<ProviderDTO, ProviderApiError>>,
		get_providers: () => Promise<TauRpcResult<ProviderDTO[], ProviderApiError>>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "result",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }

