// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
export type ContentDTO = {
	id: number,
	parent_id: string | null,
	parent: MediaItemDTO | null,
	type: string,
	description: string,
};

export type ImageDTO = {
	url: string,
	server_id: string | null,
	provider: ProviderDTO | null,
	type: string,
	media_items: MediaItemDTO[] | null,
};

export type MediaItemDTO = {
	uuid: string,
	type: string,
	outlineGradient: string,
	loaded: boolean,
	local: string,
	original: OriginalDTO[] | null,
	content: ContentDTO[] | null,
	providers: ProviderDTO[] | null,
	images: ImageDTO[] | null,
	children: MediaItemDTO[] | null,
	parents: MediaItemDTO[] | null,
};

export type OriginalDTO = {
	id: number,
	parent_id: string | null,
	parent: MediaItemDTO | null,
	server_id: string,
	uuid: string,
	url: string,
};

export type ProviderDTO = {
	server_id: string,
	user_id: string,
	type: string,
	url: string,
	media_items: MediaItemDTO[] | null,
	images: ImageDTO[] | null,
};
const ARGS_MAP = {"content":{"get_content":[]},"image":{"get_images":[]},"mediaItem":{"get_media_items":[]},"original":{"get_original":[]},"provider":{"get_providers":[]}};

const RESULT_MAP = {"content":{"get_content":false},"image":{"get_images":false},"mediaItem":{"get_media_items":false},"original":{"get_original":false},"provider":{"get_providers":false}};

export type Router = {
	content: {
		get_content: () => Promise<ContentDTO>,
	},
	image: {
		get_images: () => Promise<ImageDTO>,
	},
	mediaItem: {
		get_media_items: () => Promise<MediaItemDTO>,
	},
	original: {
		get_original: () => Promise<OriginalDTO>,
	},
	provider: {
		get_providers: () => Promise<ProviderDTO>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }

