catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
  vite-plus: 1.1.0
minimumReleaseAgeExclude:
  - "@lucide/svelte@1.55.0"
  - "@types/node@26.6.5"
  - uuid@14.0.3
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
