use jellyfin_sdk_rs::{
    self as sdk,
    apis::configuration::Configuration,
    models::{self, BaseItemDtoQueryResult},
};
use uuid::Uuid;

use crate::jellyfin_provider::JellyfinProviderError;

#[bon::builder]
pub async fn get_items_request(
    configuration: &Configuration,
    user_id: Option<&str>,
    max_official_rating: Option<&str>,
    has_theme_song: Option<bool>,
    has_theme_video: Option<bool>,
    has_subtitles: Option<bool>,
    has_special_feature: Option<bool>,
    has_trailer: Option<bool>,
    adjacent_to: Option<&str>,
    index_number: Option<i32>,
    parent_index_number: Option<i32>,
    has_parental_rating: Option<bool>,
    is_hd: Option<bool>,
    is4_k: Option<bool>,
    location_types: Option<Vec<models::LocationType>>,
    exclude_location_types: Option<Vec<models::LocationType>>,
    is_missing: Option<bool>,
    is_unaired: Option<bool>,
    min_community_rating: Option<f64>,
    min_critic_rating: Option<f64>,
    min_premiere_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    min_date_last_saved: Option<chrono::DateTime<chrono::FixedOffset>>,
    min_date_last_saved_for_user: Option<chrono::DateTime<chrono::FixedOffset>>,
    max_premiere_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    has_overview: Option<bool>,
    has_imdb_id: Option<bool>,
    has_tmdb_id: Option<bool>,
    has_tvdb_id: Option<bool>,
    is_movie: Option<bool>,
    is_series: Option<bool>,
    is_news: Option<bool>,
    is_kids: Option<bool>,
    is_sports: Option<bool>,
    exclude_item_ids: Option<Vec<Uuid>>,
    start_index: Option<i32>,
    limit: Option<i32>,
    recursive: Option<bool>,
    search_term: Option<&str>,
    sort_order: Option<Vec<models::SortOrder>>,
    parent_id: Option<&str>,
    fields: Option<Vec<models::ItemFields>>,
    exclude_item_types: Option<Vec<models::BaseItemKind>>,
    include_item_types: Option<Vec<models::BaseItemKind>>,
    filters: Option<Vec<models::ItemFilter>>,
    is_favorite: Option<bool>,
    media_types: Option<Vec<models::MediaType>>,
    image_types: Option<Vec<models::ImageType>>,
    sort_by: Option<Vec<models::ItemSortBy>>,
    is_played: Option<bool>,
    genres: Option<Vec<String>>,
    official_ratings: Option<Vec<String>>,
    tags: Option<Vec<String>>,
    years: Option<Vec<i32>>,
    enable_user_data: Option<bool>,
    image_type_limit: Option<i32>,
    enable_image_types: Option<Vec<models::ImageType>>,
    person: Option<&str>,
    person_ids: Option<Vec<Uuid>>,
    person_types: Option<Vec<String>>,
    studios: Option<Vec<String>>,
    artists: Option<Vec<String>>,
    exclude_artist_ids: Option<Vec<Uuid>>,
    artist_ids: Option<Vec<Uuid>>,
    album_artist_ids: Option<Vec<Uuid>>,
    contributing_artist_ids: Option<Vec<Uuid>>,
    albums: Option<Vec<String>>,
    album_ids: Option<Vec<Uuid>>,
    ids: Option<Vec<Uuid>>,
    video_types: Option<Vec<models::VideoType>>,
    min_official_rating: Option<&str>,
    is_locked: Option<bool>,
    is_place_holder: Option<bool>,
    has_official_rating: Option<bool>,
    collapse_box_set_items: Option<bool>,
    min_width: Option<i32>,
    min_height: Option<i32>,
    max_width: Option<i32>,
    max_height: Option<i32>,
    is3_d: Option<bool>,
    series_status: Option<Vec<models::SeriesStatus>>,
    name_starts_with_or_greater: Option<&str>,
    name_starts_with: Option<&str>,
    name_less_than: Option<&str>,
    studio_ids: Option<Vec<Uuid>>,
    genre_ids: Option<Vec<Uuid>>,
    audio_languages: Option<Vec<String>>,
    subtitle_languages: Option<Vec<String>>,
    enable_total_record_count: Option<bool>,
    enable_images: Option<bool>,
) -> Result<BaseItemDtoQueryResult, JellyfinProviderError> {
    match sdk::apis::library_api::get_items(
        &configuration,
        user_id,
        max_official_rating,
        has_theme_song,
        has_theme_video,
        has_subtitles,
        has_special_feature,
        has_trailer,
        adjacent_to,
        index_number,
        parent_index_number,
        has_parental_rating,
        is_hd,
        is4_k,
        location_types,
        exclude_location_types,
        is_missing,
        is_unaired,
        min_community_rating,
        min_critic_rating,
        min_premiere_date,
        min_date_last_saved,
        min_date_last_saved_for_user,
        max_premiere_date,
        has_overview,
        has_imdb_id,
        has_tmdb_id,
        has_tvdb_id,
        is_movie,
        is_series,
        is_news,
        is_kids,
        is_sports,
        exclude_item_ids,
        start_index,
        limit,
        recursive,
        search_term,
        sort_order,
        parent_id,
        fields,
        exclude_item_types,
        include_item_types,
        filters,
        is_favorite,
        media_types,
        image_types,
        sort_by,
        is_played,
        genres,
        official_ratings,
        tags,
        years,
        enable_user_data,
        image_type_limit,
        enable_image_types,
        person,
        person_ids,
        person_types,
        studios,
        artists,
        exclude_artist_ids,
        artist_ids,
        album_artist_ids,
        contributing_artist_ids,
        albums,
        album_ids,
        ids,
        video_types,
        min_official_rating,
        is_locked,
        is_place_holder,
        has_official_rating,
        collapse_box_set_items,
        min_width,
        min_height,
        max_width,
        max_height,
        is3_d,
        series_status,
        name_starts_with_or_greater,
        name_starts_with,
        name_less_than,
        studio_ids,
        genre_ids,
        audio_languages,
        subtitle_languages,
        enable_total_record_count,
        enable_images,
    )
    .await
    {
        Ok(response) => Ok(response),
        Err(err) => Err(JellyfinProviderError::ApiEntryRetrievalError(Some(
            err.to_string(),
        ))),
    }
}
