[package]
name = "journey-provider"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
reqwest = {workspace = true}
chrono = {workspace = true}
url = {workspace = true}
bon = {workspace = true}
uuid = {workspace = true}
journey-db = { path = "../journey-db" }
jellyfin-sdk-rs = { git = "https://github.com/leuchthelp/jellyfin-sdk-rs" }
