[package]
name = "journey-provider"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
tauri-plugin-os = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
bon = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
dotenvy = { workspace = true }
journey-db = { workspace = true }
journey-utils = { workspace = true }
journey-keyring = { workspace = true }
jellyfin-sdk-rs = { git = "https://github.com/leuchthelp/jellyfin-sdk-rs" }

[dev-dependencies]
tokio = { workspace = true }
serial_test = { workspace = true }
