// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
const ARGS_MAP = {"":{}};

const RESULT_MAP = {"":{}};

export type Router = {
	"": Record<string, never>,
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }

