[package]
name = "journey-db"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bon = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
inherent = { workspace = true }
thiserror = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

taurpc = { workspace = true }
specta = { workspace = true }
